version: "3"

services:
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    env_file:
      - .env.local
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --innodb-use-native-aio=0
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/local:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports: 
      - "8080:8080"
    volumes:
      - .:/go/src/todo_server
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    env_file:
      - .env.local
    depends_on: 
      - db
    command: ./todo_server
